## Data Cleaning and Feature Engineering

### Import Python Libraries and set properties for the notebook

In [68]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from matplotlib.ticker import MaxNLocator
import matplotlib.dates as mdates

In [69]:
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_rows', None)     # Show all rows

### Import data from the raw file

In [70]:
filepath = '../data/raw/neiss_combined_raw_untouched_data.csv'
data_original = pd.read_csv(filepath, engine='pyarrow')

In [71]:
# Deep copy to preserve original data
data = data_original.copy()
data1 = data_original.copy()

In [72]:
data1.columns

Index(['data_year', 'CPSC_Case_Number', 'Treatment_Date', 'Age', 'Sex', 'Race',
       'Other_Race', 'Hispanic', 'Body_Part', 'Diagnosis', 'Other_Diagnosis',
       'Body_Part_2', 'Diagnosis_2', 'Other_Diagnosis_2', 'Disposition',
       'Location', 'Fire_Involvement', 'Product_1', 'Product_2', 'Product_3',
       'Alcohol', 'Drug', 'Narrative_1', 'Stratum', 'PSU', 'Weight'],
      dtype='str')

In [73]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 7315732 entries, 0 to 7315731
Data columns (total 26 columns):
 #   Column             Dtype
---  ------             -----
 0   data_year          int64
 1   CPSC_Case_Number   int64
 2   Treatment_Date     object
 3   Age                int64
 4   Sex                int64
 5   Race               int64
 6   Other_Race         str
 7   Hispanic           float64
 8   Body_Part          int64
 9   Diagnosis          int64
 10  Other_Diagnosis    str
 11  Body_Part_2        float64
 12  Diagnosis_2        float64
 13  Other_Diagnosis_2  str
 14  Disposition        int64
 15  Location           int64
 16  Fire_Involvement   int64
 17  Product_1          int64
 18  Product_2          int64
 19  Product_3          int64
 20  Alcohol            float64
 21  Drug               float64
 22  Narrative_1        str
 23  Stratum            str
 24  PSU                int64
 25  Weight             float64
dtypes: float64(6), int64(14), object(1), str(5)
memory usage: 2.0+ GB

### 1. Handling NULL Data in the file <br>

In [74]:
null_data = data.isnull().sum().reset_index()
null_data.columns = ['Column_Name', 'Count']
null_data = null_data[null_data['Count'] > 0]
null_data

          Column_Name    Count
6          Other_Race  6821041
7            Hispanic  5283928
10    Other_Diagnosis  6329255
11        Body_Part_2  6866693
12        Diagnosis_2  6866693
13  Other_Diagnosis_2  7214095
20            Alcohol  5283928
21               Drug  5283928

#### The above list of features have null values that needs to be handled. <br>

#### 1.1 NULL Values in Other_Race Feature
Other Race feature is a string field which lists the description of other race if the race used in the Race field is 3. Hence, update the Other_Race with a NULL value as "UNKNOWN"

In [75]:
print(f'Null values in Other_Race Feature before change:{data1["Other_Race"].isnull().sum()}') 
data1['Other_Race'] = data1['Other_Race'].fillna('UNKNOWN')
print(f'Null values in Other_Race Feature after change:{data1["Other_Race"].isnull().sum()}')

Null values in Other_Race Feature before change:6821041
Null values in Other_Race Feature after change:0

#### 1.2. Handle NULL values in Hispanic Feature

Fill the NULL records with 0.0 - Unknown.

In [76]:
print(data1.Hispanic.value_counts())
print(f'Null values in Hispanic Feature before change:{data1["Hispanic"].isnull().sum()}') 
data1['Hispanic'] = data1['Hispanic'].fillna('0.0')
data1['Hispanic'] = data1['Hispanic'].astype(float)
print(f'Null values in Hispanic Feature after change:{data1["Hispanic"].isnull().sum()}')
print(data1.Hispanic.value_counts())

Hispanic
2.0    1231235
0.0     586760
1.0     213809
Name: count, dtype: int64
Null values in Hispanic Feature before change:5283928
Null values in Hispanic Feature after change:0
Hispanic
0.0    5870688
2.0    1231235
1.0     213809
Name: count, dtype: int64

#### 1.3 Handle NULL values in Other_Diagnosis Feature

In [77]:
print(f'Null values in Other_Diagnosis Feature before change:{data1["Other_Diagnosis"].isnull().sum()}') 
data1['Other_Diagnosis'] = data1['Other_Diagnosis'].fillna('UNKNOWN')
print(f'Null values in Other_Diagnosis Feature after change:{data1["Other_Diagnosis"].isnull().sum()}')

Null values in Other_Diagnosis Feature before change:6329255
Null values in Other_Diagnosis Feature after change:0

#### 1.4. Handle NULL values in Body_Part_2 Feature

In [78]:
print(f'Null values in Body_Part_2 Feature before change:{data1["Body_Part_2"].isnull().sum()}') 
data1['Body_Part_2'] = data1['Body_Part_2'].fillna('87')
print(f'Null values in Body_Part_2 Feature after change:{data1["Body_Part_2"].isnull().sum()}')

Null values in Body_Part_2 Feature before change:6866693
Null values in Body_Part_2 Feature after change:0

#### 1.5. Handle NULL values in Diagnosis_2 Feature

In [79]:
print(f'Null values in Diagnosis_2 Feature before change:{data1["Diagnosis_2"].isnull().sum()}') 
data1['Diagnosis_2'] = data1['Diagnosis_2'].fillna(71.0)
print(f'Null values in Diagnosis_2 Feature after change:{data1["Diagnosis_2"].isnull().sum()}')

Null values in Diagnosis_2 Feature before change:6866693
Null values in Diagnosis_2 Feature after change:0

#### 1.6. Handle NULL values in Other_Diagnosis_2 Feature

In [80]:
print(f'Null values in Other_Diagnosis_2 Feature before change:{data1["Other_Diagnosis_2"].isnull().sum()}') 
data1['Other_Diagnosis_2'] = data1['Other_Diagnosis_2'].fillna('UNKNOWN')
print(f'Null values in Other_Diagnosis_2 Feature after change:{data1["Other_Diagnosis_2"].isnull().sum()}')

Null values in Other_Diagnosis_2 Feature before change:7214095
Null values in Other_Diagnosis_2 Feature after change:0

#### 1.7. Handle NULL values in the Alcohol Feature

In [81]:
print(f'Null values in Alcohol Feature before change:{data1["Alcohol"].isnull().sum()}') 
data1['Alcohol'] = data1['Alcohol'].fillna(3)
print(f'Null values in Alcohol Feature after change:{data1["Alcohol"].isnull().sum()}') 
print(data1['Alcohol'].value_counts())

Null values in Alcohol Feature before change:5283928
Null values in Alcohol Feature after change:0
Alcohol
3.0    5283928
0.0    1993098
1.0      38706
Name: count, dtype: int64

#### 1.8. Null values in the Drug Feature

In [82]:
print(f'Null values in Drug Feature before change:{data1["Drug"].isnull().sum()}') 
data1['Drug'] = data1['Drug'].fillna(3)
print(f'Null values in Alcohol Feature after change:{data1["Drug"].isnull().sum()}') 
print(data1['Drug'].value_counts())

Null values in Drug Feature before change:5283928
Null values in Alcohol Feature after change:0
Drug
3.0    5283928
0.0    1986756
1.0      45048
Name: count, dtype: int64

#### Validate if all the null values are fixed

In [91]:
null_data = data1.isnull().sum().reset_index()
null_data.columns = ['Column_Name', 'Null Value Count']
null_data = null_data[null_data['Null Value Count'] == 0]
null_data

          Column_Name  Null Value Count
0           data_year                 0
1    CPSC_Case_Number                 0
2      Treatment_Date                 0
3                 Age                 0
4                 Sex                 0
5                Race                 0
6          Other_Race                 0
7            Hispanic                 0
8           Body_Part                 0
9           Diagnosis                 0
10    Other_Diagnosis                 0
11        Body_Part_2                 0
12        Diagnosis_2                 0
13  Other_Diagnosis_2                 0
14        Disposition                 0
15           Location                 0
16   Fire_Involvement                 0
17          Product_1                 0
18          Product_2                 0
19          Product_3                 0
20            Alcohol                 0
21               Drug                 0
22        Narrative_1                 0
23            Stratum                 0
24                PSU                 0
25             Weight                 0
26       Hospitalized                 0

No null values exist in the data.

### 2. Feature Engineering

### 2.1 Add Hospitalization Feature

To develop statistically sound predictive models to reliably identify factors associated with hospitalization of product-related injuries; we need to create a target variable for Hospitalized (Yes/No) for each injury reported based on the disposition code.

In [84]:
# B. Define Target Variable (Hospitalization)
# Disposition Codes:
# 1=Released, 2=Transferred, 4=Hospitalized, 5=Held for Obs, 6=Left, 8=Fatality
# We group 2, 4, 5, and 8 as "Severe/Hospitalized"
disposition_codes = [2, 4, 5, 8]
data1['Hospitalized'] = data1['Disposition'].apply(lambda x: 1 if x in disposition_codes else 0)

In [85]:
Hospitalized_df = data1.Hospitalized.value_counts(normalize=True).reset_index()
Hospitalized_df.columns = ['Hospitalized', 'Percentage']
print(Hospitalized_df)

   Hospitalized  Percentage
0             0    0.909104
1             1    0.090896

Data is unbalanced and we need to use any of the below techniques to balance the dataset.
1. Use the "class weight" parameter 
2. Use SMOTE (Oversampling) method 
3. Under Sampling - use all of the hospitalized data and take equal number of not_hospitalized data randomly. Could cause uncertain results.

#### 2.2 Add True Alcohol Flag

# Fill missing values in 'Alcohol' column with 3 (indicating 'Not Recorded')
data1['Alcohol_Flag'] = data1['Alcohol'].fillna(3)
data1['Alcohol_bool'] = data1['Alcohol'].map({1: True, 0: False})
print(data1['Alcohol_Flag'].value_counts())
print(data1['Alcohol'].value_counts())
print(data1['Alcohol_bool'].value_counts())

# Create a list of keywords (standard NEISS abbreviations)
alcohol_keywords = [
    # Medical & Formal
    'ALCOHOL', 'ETOH', 'INTOXICATED', 'INEBRIATED', 'DRUNK', 
    'SOBER', # Often appears as "Not Sober" or "Sobering up"
    'BAC ',  # Blood Alcohol Content (Need the space to avoid 'BACK')
    
    # Beverages
    'BEER', 'WINE', 'LIQUOR', 'VODKA', 'WHISKEY', 'WHISKY', 
    'TEQUILA', 'RUM', 'GIN', 'BRANDY', 'CHAMPAGNE', 'MOONSHINE',
    
    # Actions/Context
    'DRINKING', 'PARTY', 'BAR', 'PUB', 'CLUB', 'TAVERN',
    'HAPPY HOUR', 'KEG'
]

# Create a new column that searches the Narrative for these words
# Returns True if found, False if not
data1['Alcohol_Text_Flag'] = data['Narrative_1'].str.contains('|'.join(alcohol_keywords), case=False, na=False)
data1['Alcohol_Text_Flag'] = data1['Alcohol_Text_Flag'].astype(float)

# Check how many you found
#data1['True_Alcohol_Flag'] = data1['Alcohol_bool'] | data1['Alcohol_Text_Flag']
print(data1['Alcohol_Text_Flag'].value_counts())
print(data1['Alcohol_Flag'].value_counts())

data1['True_Alcohol_Flag'] = data1['Alcohol_Text_Flag'] + data1['Alcohol_Flag']
print(data1['True_Alcohol_Flag'].value_counts())
data1['True_Alcohol_Flag'] = data1['True_Alcohol_Flag'].map({0.0:0.0,1.0: 1.0, 2.0: 1.0, 3.0: 2.0, 4.0: 1.0})
print(data1['True_Alcohol_Flag'].value_counts())

data1.drop(columns = ['Alcohol_Text_Flag','Alcohol_bool','Alcohol_Flag'], inplace=True)
data1.isna().sum()

#### 2.3 Add True Drug Flag

# 1. Define keywords for common substances & slang
drug_keywords = [
    # General Terms
    'DRUG', 'OVERDOSE', 'MEDICATION', 'PILL', 'TABLET', 'CAPSULE', 
    'INGEST', 'SUBSTANCE', 'NARCOTIC', 'OPIOID', 'OPIGTE', # Common typo
    
    # Street / Illegal
    'COCAINE', 'HEROIN', 'METHAMPHETAMINE', 'MARIJUANA', 'CANNABIS', 
    'FENTANYL', 'ECSTASY', 'MDMA', ' LSD ', ' PCP ', 'HASHISH',
    
    # Prescription / OTC (Brand & Generic)
    'XANAX', 'VALIUM', 'PERCOCET', 'VICODIN', 'OXYCODONE', 'OXYCONTIN',
    'ADDERALL', 'RITALIN', 'TYLENOL', 'ASPIRIN', 'IBUPROFEN', 'ADVIL',
    'MOTRIN', 'BENADRYL', 'INSULIN', 'VITAMIN', 'MORPHINE', 'CODEINE'
]
# 2. Create the Search Pattern (joins them with OR logic: "DRUG|OVERDOSE|...")
pattern = '|'.join(drug_keywords)
# 3. Create a True/False column based on the text
data1['Drug_flag'] = data1['Narrative_1'].str.contains(pattern, case=False, na=False)
print(data1.Drug_flag.value_counts())
print(data1['Drug'].value_counts())